### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'data/qg.tgt.dict'

### ISSUE THREAD

**Issue by SeekPoint** [xinyadu/nqg#18]
mldl@mldlUB1604:~/ub16_prj/nqg/paragraph$ bash preprocess_embedding.sh 
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 52, in main
    with open(args.dict, "r") as input_file:
IOError: [Errno 2] No such file or directory: 'data/qg.src.dict'

Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 52, in main
    with open(args.dict, "r") as input_file:
IOError: [Errno 2] No such file or directory: 'data/qg.tgt.dict'
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 52, in main
    with open(args.dict, "r") as input_file:
IOError: [Errno 2] No such file or directory: 'data/qg.par.dict'

**Comment by SeekPoint** [comment]
missed the preprocess

**Comment by Binathi** [comment]
> missed the preprocess

I ran the command
!th preprocess.lua -config config-preprocess
 It runs successfully but doent output anything. When I run the command 
!python preprocess_embedding.py --embedding /content/glove.6B.300d.txt --dict ./data/qg.src.dict --output ./data/qg.src.6B.300d.npy

It gives the following error
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 52, in main
    with open(args.dict, "r") as input_file:
FileNotFoundError: [Errno 2] No such file or directory: './data/qg.src.dict'
