### ISSUE TITLE
Invalid literal for float

### ISSUE THREAD

**Issue by subhammahanta777** [xinyadu/nqg#2]
After doing:

python preprocess_embedding.py --embedding data/qg-train.t7 --dict data/qg.src.dict --output data/qg.src.840B.300d.npy

error:
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 49, in main
    word2embedding[line[0]] = np.asarray(map(float, line[1 : ]))
ValueError: invalid literal for float(): 0

**Comment by payalbajaj** [comment]
Can you try with python3?

**Comment by talrose01** [comment]
i have the same error, 
using python 2,
do you have any tips to solve this error?
thanks

**Comment by SundeepPidugu** [comment]
whats the format for the text file which needs to be replaced in the `paragraph/preprocess_embedding.sh` file ??

Can i use this file ? [glove.840B.300d.txt](https://www.kaggle.com/takuok/glove840b300dtxt)

or is there a way to generate a embedding text file by my own ??
