### ISSUE TITLE
Error while th train.lua -config config-train : inconsistent tensor size, expected tensor [45004 x 300] and src [45004 x 100] to have the same number of elements, but got 13501200 and 4500400 elements respectively at */*/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:120

### ISSUE THREAD

**Issue by vedarddy** [xinyadu/nqg#24]
This is the error I get when I try to train the model! Please help!

**Comment by wentsun12** [comment]
I also got the same error. Have you solved it already?
If so, could you mind to teach me how to solve it?
Thank you very much. @vedarddy

**Comment by TjebbeVQ** [comment]
@vedarddy @wentsun12 I think i solved it. I changed the word_vec_size to 100 instead of 300 and right now its training the model. So I think that did the trick.

**Comment by hamzaLeb** [comment]
Normally the **word_vec_size=300** works fine, I've done the implementation. 
But I already had this issue when I misunderstood the `<path to embedding txt file>`. I thought it's the path to the input file but it turns out that it is the path to the file we have to download from [https://nlp.stanford.edu/projects/glove/](https://nlp.stanford.edu/projects/glove/) which name is **glove.840B.300d.zip** (about 2Go). 
The input file is rather given in the **Generating** step where you change `src=...` in the **config-trans** file to `src=path_to_your_input_sentence_text_file`

**Comment by Binathi** [comment]
@TjebbeVQ @hamzaLeb  As you implemented the code, maybe can help me with the following issue. I am trying to run the code on google colab.
When i run the preprocess command in sentence level
!th preprocess.lua -config config-preprocess

there is no output and when i run the next command
!python preprocess_embedding.py --embedding /content/glove.6B.100d.txt --dict ./data/qg.src.dict --output ./data/qg.src.6B.100d.npy

It pops up the below error
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 46, in main
    with open(args.embedding, "r") as input_file:
FileNotFoundError: [Errno 2] No such file or directory: '/content/glove.6B.100d.txt'

Can you suggest why the preprocess might not be running

**Comment by wsba17051816** [comment]
hi,body,I'd like to ask for <model file name>,what I should put in ther?Do me a favor ,please.
